services:
    _defaults:
        autowire: true
        autoconfigure: true

    Softleister\MpdftemplateBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection}
